covid19/urls.py
from django.contrib import admin
from django.urls import path, include
from web.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include("web.urls", namespace='web')),
]

web/urls.py
from django.urls import path, include
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.Home_view, name="home"),
]

web/models.py
from django.db import models


# Create your models here.
class User_gps(models.Model):
    username = models.CharField(max_length=100)
    x = models.FloatField()
    y = models.FloatField()
    timestamp = models.CharField(max_length=200)

    class Meta:
        managed = True
        db_table = 'User_gps'
        unique_together = ('username', 'x', 'y', 'timestamp')

    def __str__(self):
        return self.username + str(self.timestamp)

web/views.py
import json

from django.shortcuts import render, redirect
from django.views import View
from django.views.decorators.csrf import csrf_exempt

from .models import User_gps
from django.core import serializers


# Create your views here.

@csrf_exempt
def Home_view(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            jsonObject = json.loads(request.body)
            gps = User_gps()
            gps.username = jsonObject.get('name')
            gps.x = jsonObject.get('x')
            gps.y = jsonObject.get('y')
            gps.timestamp = jsonObject.get('timestamp')
            gps.save()

        user_datas = User_gps.objects.all().filter(username=request.user.username).values().order_by("timestamp")
        user_data = []
        for data in user_datas:
            user_data.append([data['x'], data['y'], data['timestamp']])
        print(user_data)
        return render(request, "home.html", {'user_data': user_data})
    else:
        return render(request,"home.html",{'user_data': [[]]})


class KakaoSignInView(View):
    def get(self, request):
        app_key = 'c3d32ec4bf5aefb7ad5585224c87eb91'
        redirect_uri = 'http://localhost:8000/accounts/kakao/login/callback/'
        kakao_auth_api = 'https://kauth.kakao.com/oauth/authorize?response_type=code'

        return redirect(f'{kakao_auth_api}&client_id={app_key}&redirect_uri={redirect_uri}')

templates/home.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>CO-VADE 시스템</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
<div class="container"> <!-- nav 적용 --> <p>
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#">
            <img src="{% static 'img/logo.png' %}" width="30" height="30"
                 class="d-inline-block align-top" alt="" loading="lazy">
            CO_VADE 시스템
        </a>
        <ul id="nav1" class="nav justify-content-end bg-light">
            <li class="nav-item"><a class="nav-link active" href="{% url 'web:home' %}">Home</a></li>
            {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="#">{{ user.username }}님!</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'account_logout' %}">로그아웃</a></li>
            {% else %}
                <li class="nav-item"><a class="nav-link" href="{% provider_login_url 'kakao' %}">로그인</a></li>
            {% endif %}
        </ul>
    </nav>
</div>
<div class="container">
    <div id="map" style="width:100%;height:100vh;"></div>
</div>
{{ user_data|json_script:'jsonData' }}

<script type="text/javascript"
        src="//dapi.kakao.com/v2/maps/sdk.js?appkey=01f19f54caab4ebc555210149f8f3c23&libraries=services,clusterer,drawing"></script>
<script>
    // 지도 설정 값
    var mapContainer = document.getElementById('map'), // 지도를 표시할 div
        mapOption = {
            center: new kakao.maps.LatLng(36.769909138052455, 126.93259335277044), // 지도의 중심좌표
            level: 3, // 지도의 확대 레벨
            mapTypeId: kakao.maps.MapTypeId.ROADMAP // 지도종류
        };

    // 지도를 생성한다
    var map = new kakao.maps.Map(mapContainer, mapOption);

    // 지도에 확대 축소 컨트롤을 생성한다
    var zoomControl = new kakao.maps.ZoomControl();

    // 지도의 우측에 확대 축소 컨트롤을 추가한다
    map.addControl(zoomControl, kakao.maps.ControlPosition.RIGHT);


    //코로나19 확진자 방문위치 마커(데이터)
    // 마커 클러스터러를 생성합니다
    var clusterer = new kakao.maps.MarkerClusterer({
        map: map, // 마커들을 클러스터로 관리하고 표시할 지도 객체
        averageCenter: true, // 클러스터에 포함된 마커들의 평균 위치를 클러스터 마커 위치로 설정
        minLevel: 10 // 클러스터 할 최소 지도 레벨
    });

    var mapdata = [
        [36.76902948513177, 126.93484769177441, '<div style="padding: 5px">멀티미디어관 5층</div>'],
        [36.77166729116676, 126.93688662748794, '<div style="padding: 5px">경희학성아파트</div>'],
        [36.77409534418264, 126.93263870470379, '<div style="padding: 5px">롯데리아 신창점</div>'],
        [36.76950525304196, 126.95109033476949, '<div style="padding: 5px">신창역</div>'],
    ];

    var markers = [];

    for (var i = 0; i < mapdata.length; i++) {
        // 지도에 마커를 생성하고 표시한다
        var imageSrc = "{% static "img/patient.png" %}", // 마커이미지의 주소입니다
            imageSize = new kakao.maps.Size(25, 35), // 마커이미지의 크기입니다
            imageOption = {offset: new kakao.maps.Point(27, 69)}; // 마커이미지의 옵션입니다. 마커의 좌표와 일치시킬 이미지 안에서의 좌표를 설정합니다.

        // 마커의 이미지정보를 가지고 있는 마커이미지를 생성합니다
        var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize, imageOption),
            markerPosition = new kakao.maps.LatLng(37.54699, 127.09598); // 마커가 표시될 위치입니다

        // 마커를 생성하고 지도에 표시합니다
        var marker = new kakao.maps.Marker({
            map: map,
            image: markerImage, // 마커이미지 설정
            position: new kakao.maps.LatLng(mapdata[i][0], mapdata[i][1])
        });

        // 인포윈도우를 생성합니다
        var infowindow = new kakao.maps.InfoWindow({
            content: mapdata[i][2]
        });

        // 마커 위에 인포윈도우를 표시합니다. 두번째 파라미터인 marker를 넣어주지 않으면 지도 위에 표시됩니다
        markers.push(marker);

        // 마커에 mouseover 이벤트와 mouseout 이벤트를 등록합니다
        // 이벤트 리스너로는 클로저를 만들어 등록합니다
        // for문에서 클로저를 만들어 주지 않으면 마지막 마커에만 이벤트가 등록됩니다
        kakao.maps.event.addListener(marker, 'mouseover', makeOverListener(map, marker, infowindow));
        kakao.maps.event.addListener(marker, 'mouseout', makeOutListener(infowindow));
    }

    // 클러스터러에 마커들을 추가합니다
    clusterer.addMarkers(markers);

    // 인포윈도우를 표시하는 클로저를 만드는 함수입니다
    function makeOverListener(map, marker, infowindow) {
        return function () {
            infowindow.open(map, marker);
        };
    }

    // 인포윈도우를 닫는 클로저를 만드는 함수입니다
    function makeOutListener(infowindow) {
        return function () {
            infowindow.close();
        };
    }


    //코로나 선별 진료소 마커(검색)
    // 마커를 클릭하면 장소명을 표출할 인포윈도우 입니다
    var infowindow = new kakao.maps.InfoWindow({zIndex: 1});

    // 장소 검색 객체를 생성합니다
    var ps = new kakao.maps.services.Places();

    // 키워드로 장소를 검색합니다
    ps.keywordSearch('아산코로나검사소', placesSearchCB);

    // 키워드 검색 완료 시 호출되는 콜백함수 입니다
    function placesSearchCB(data, status, pagination) {
        if (status === kakao.maps.services.Status.OK) {
            // 검색된 장소 위치를 기준으로 지도 범위를 재설정하기위해
            // LatLngBounds 객체에 좌표를 추가합니다
            var bounds = new kakao.maps.LatLngBounds();

            for (var i = 0; i < data.length; i++) {
                displayMarker(data[i]);
                bounds.extend(new kakao.maps.LatLng(data[i].y, data[i].x));
            }

        }
    }

    // 지도에 마커를 표시하는 함수입니다
    function displayMarker(place) {
        var imageSrc = "{% static "img/hospital.png" %}", // 마커이미지의 주소입니다
            imageSize = new kakao.maps.Size(25, 35), // 마커이미지의 크기입니다
            imageOption = {offset: new kakao.maps.Point(27, 69)}; // 마커이미지의 옵션입니다. 마커의 좌표와 일치시킬 이미지 안에서의 좌표를 설정합니다.

        // 마커의 이미지정보를 가지고 있는 마커이미지를 생성합니다
        var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize, imageOption),
            markerPosition = new kakao.maps.LatLng(37.54699, 127.09598); // 마커가 표시될 위치입니다

        // 마커를 생성하고 지도에 표시합니다
        var marker = new kakao.maps.Marker({
            map: map,
            image: markerImage, // 마커이미지 설정
            position: new kakao.maps.LatLng(place.y, place.x)
        });

        // 마커에 클릭이벤트를 등록합니다
        kakao.maps.event.addListener(marker, 'click', function () {
            // 마커를 클릭하면 장소명이 인포윈도우에 표출됩니다
            infowindow.setContent('<div style="padding:5px;font-size:12px;">' + place.place_name + '</div>');
            infowindow.open(map, marker);
        });
    }


    // 지도에 확진자 동선 표시
    // 사용자 이동 데이터(좌표,시간)
    var gps = JSON.parse(document.getElementById('jsonData').textContent)
    var gpsdata = {{ user_data|safe }};

    // 선을 구성하는 좌표 배열입니다. 이 좌표들을 이어서 선을 표시합니다
    var linePath = [];

    for (var i = 0; i < gpsdata.length; i++) {
        linePath.push(new kakao.maps.LatLng(gpsdata[i][0], gpsdata[i][1]));
    }

    // 지도에 표시할 선을 생성합니다
    var polyline = new kakao.maps.Polyline({
        path: linePath, // 선을 구성하는 좌표배열 입니다
        strokeWeight: 2, // 선의 두께 입니다
        strokeColor: '#fb7c01', // 선의 색깔입니다
        strokeOpacity: 1, // 선의 불투명도 입니다 1에서 0 사이의 값이며 0에 가까울수록 투명합니다
        strokeStyle: 'solid' // 선의 스타일입니다
    });

    // 지도에 선을 표시합니다
    polyline.setMap(map);

    //이동경로 점 표시
    var markers = [];

    for (var i = 0; i < gpsdata.length; i++) {
        // 지도에 마커를 생성하고 표시한다
        var imageSrc = "{% static "img/ex.png" %}", // 마커이미지의 주소입니다
            imageSize = new kakao.maps.Size(7, 7), // 마커이미지의 크기입니다
            imageOption = {offset: new kakao.maps.Point(3, 3)}; // 마커이미지의 옵션입니다. 마커의 좌표와 일치시킬 이미지 안에서의 좌표를 설정합니다.

        // 마커의 이미지정보를 가지고 있는 마커이미지를 생성합니다
        var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize, imageOption),
            markerPosition = new kakao.maps.LatLng(0, 0); // 마커가 표시될 위치입니다

        // 마커를 생성하고 지도에 표시합니다
        var marker = new kakao.maps.Marker({
            map: map,
            image: markerImage, // 마커이미지 설정
            position: new kakao.maps.LatLng(gpsdata[i][0], gpsdata[i][1])
        });

        // 인포윈도우를 생성합니다
        var infowindow = new kakao.maps.InfoWindow({
            content: gpsdata[i][2]
        });

        // 마커 위에 인포윈도우를 표시합니다. 두번째 파라미터인 marker를 넣어주지 않으면 지도 위에 표시됩니다
        markers.push(marker);

        // 마커에 mouseover 이벤트와 mouseout 이벤트를 등록합니다
        // 이벤트 리스너로는 클로저를 만들어 등록합니다
        // for문에서 클로저를 만들어 주지 않으면 마지막 마커에만 이벤트가 등록됩니다
        kakao.maps.event.addListener(marker, 'mouseover', makeOverListener(map, marker, infowindow));
        kakao.maps.event.addListener(marker, 'mouseout', makeOutListener(infowindow));
    }

    // 클러스터러에 마커들을 추가합니다
    clusterer.addMarkers(markers);
</script>
{% if user.is_authenticated %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script>
        var time = 60000; //1초(1000) * 60
        setInterval("autoScript()", time);

        function autoScript() {
            navigator.geolocation.getCurrentPosition((position) => {
                let latitude = position.coords.latitude;
                let longitude = position.coords.longitude;

                let today = new Date();

                let hours = today.getHours(); // 시
                let minutes = today.getMinutes();  // 분
                let timestamp = hours.toString() + ":" + minutes.toString();

                let param = {
                    'name': "{{ user.username }}",
                    'x': latitude,
                    'y': longitude,
                    'timestamp': timestamp
                }

                $.ajax({
                    url: '{% url "web:home" %}',
                    type: 'POST',
                    data: JSON.stringify(param),
                    error: function () {
                        alert('전송 실패')
                    }
                });

            }, (err) => {

            });
            location.reload();
        }
    </script>
{% endif %}
</body>
</html>